In [6]:
import numpy as np

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,10,3)   #linspace- Return evenly spaced numbers over a specified interval

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [21]:
np.eye(4)    #eye creates an identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(2)   #random number arrays

array([0.6994106 , 0.22203833])

In [23]:
np.random.rand(5,5)

array([[0.0653203 , 0.39215157, 0.98044672, 0.67234132, 0.041906  ],
       [0.42137884, 0.42869774, 0.28449807, 0.26297983, 0.80323693],
       [0.8783585 , 0.92801201, 0.85765196, 0.03775553, 0.41632423],
       [0.23088667, 0.62685653, 0.25540596, 0.5536479 , 0.92219509],
       [0.8548901 , 0.50305882, 0.08775067, 0.11642017, 0.94394405]])

In [24]:
np.random.randn(2)

array([ 0.95141776, -0.72085572])

In [25]:
np.random.randn(5,5)

array([[ 1.6163285 ,  0.86938124, -0.77234083,  0.05626146,  0.56045409],
       [-1.00082708, -1.84552009,  1.66672799, -0.15811706,  0.85993932],
       [ 0.46791238, -0.4902798 ,  2.07262364, -0.18779098,  0.53245392],
       [ 1.00284277,  1.37183619,  0.59493101, -0.24121734, -0.42193266],
       [-0.78857586, -0.16860283,  0.95878661, -1.01599966, -0.07277593]])

In [26]:
np.random.randint(1,100)

2

In [27]:
np.random.randint(1,100,10)

array([76, 81,  2, 96, 89, 88, 79, 77, 38,  2], dtype=int32)

In [39]:
arr = np.arange(25)

ranarr = np.random.randint(0,50,10)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([23, 12,  7, 23, 32, 49, 36, 26, 16, 38], dtype=int32)

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([23, 12,  7, 23, 32, 49, 36, 26, 16, 38], dtype=int32)

In [45]:
ranarr.max()

np.int32(49)

In [46]:
ranarr.argmax()

np.int64(5)

In [50]:
ranarr

array([23, 12,  7, 23, 32, 49, 36, 26, 16, 38], dtype=int32)

In [51]:
ranarr.min()

np.int32(7)

In [52]:
ranarr.argmin()

np.int64(2)

In [54]:

arr.shape

(25,)

In [56]:
#Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
arr.reshape(1,25).shape

(1, 25)

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [59]:
arr.reshape(25,1).shape

(25, 1)

In [60]:
arr.dtype

dtype('int64')