In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

np.int64(8)

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[0:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#Important notes on Slices
slice_of_arr = arr[0:6]


In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:]=99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
##Indexing a 2D array (matrices)

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[1]

array([20, 25, 30])

In [22]:
arr_2d[1][0]

np.int64(20)

In [23]:
arr_2d[1,0]

np.int64(20)

In [24]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr_2d[2]

array([35, 40, 45])

In [27]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[2]

array([35, 40, 45])

In [32]:
#Fancy Indexing
#Set up matrix
arr2d = np.zeros((10,10))

In [37]:
for i in range(10):
    arr2d[i] = i

In [38]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [39]:
#Length of array
arr_length=arr2d.shape[1]

In [40]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [41]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [42]:
arr = np.arange(1,11)       #Selection - How to use brackets
arr       #Selection - How to use brackets

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr=arr>4

In [45]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])